### ISSUE TITLE
Initial guesses to redefine_critical_parameters()

### ISSUE THREAD

**Issue by vegardjervell** [SINTEF/thermopack#20]
Would it be possible (read: Not too much effort) to enable passing initial guesses to the `redefine_critical_parameters` function? The primary usage I'm thinking of is modeling the behaviour of hypothetical LJ-, Mie- or hard-sphere fluids where the (dimensionless) critical parameters are known. This would make it possible to easily investigate the effects of changing the potential parameters while using placeholders without having trouble with the critical point solver not converging if the parameters are changed too much.

My current solution is iteratively changing the parameters and calling `redefine_critical_parameters` until I've gotten to the parameters I want to test.

Again, this is just a thought on functionality that could be useful, not anything _critical_ ;)

**Comment by morteham** [comment]
Hi!

Adding this functionality to `redefine_critical_parameters` should be a minor task. I will add soon.

Regards,
Morten
