### ISSUE TITLE
Global phase diagram for SAFT-VRQ

### ISSUE THREAD

**Issue by ianhbell** [SINTEF/thermopack#24]
I'm having a hard time getting the right global phase diagrams for neon + hydrogen and helium + hydrogen with ThermoPack.  I'm trying to use the SAFT-VRQ model to build the global phase diagram, but I am getting a Type I mixture for neon + hydrogen which doesn't agree with the experiments or the figures in the paper from Aasen.

My guess is that the interaction parameters implemented by default in ThermoPack are default ones, but in the paper different ones appear to be used. I couldn't find a method in the python interface to change the interaction parameters, or to query them either.  Could you please let me know how I can do this?

Thanks!

My python code is below:

```python
# Importing pyThermopack
from pyctp import saftvrqmie

# Importing Numpy (math, arrays, etc...)
import numpy as np

# Importing Matplotlib (plotting)
import matplotlib.pyplot as plt

for pair in ['Ne,H2', 'He,H2']:

    # Instantiate and init SAFT-VRQ Mie object
    qSAFT = saftvrqmie.saftvrqmie()
    qSAFT.init(pair)
    print(dir(qSAFT))
    qSAFT.set_tmin(temp=2.0)

    KSTYPE, VLE, LLVE, CRIT, AZ = qSAFT.global_binary_plot(minimum_pressure=1.0e5, minimum_temperature=2.0, include_azeotropes=True)
    p_scaling = 1.0e-6
    colors = [ "black", "blue", "red", "green"]
    linestyles = [ "-", "--", ":", "-."]
    label = "VLE"
    for i in range(len(VLE)):
        plt.plot(VLE[i][:,0], VLE[i][:,1]*p_scaling, linestyle=linestyles[0],
                 color=colors[0], label=label)
        label = None

    label = "VLLE"
    for i in range(len(LLVE)):
        plt.plot(LLVE[i][:,0], LLVE[i][:,1]*p_scaling, linestyle=linestyles[1],
                 color=colors[1], label=label)
        label = None

    label = "Critical"
    for i in range(len(CRIT)):
        plt.plot(CRIT[i][:,0], CRIT[i][:,1]*p_scaling, linestyle=linestyles[2],
                 color=colors[2], label=label)
        label = None

    label = "AZ"
    for i in range(len(AZ)):
        plt.plot(AZ[i][:,0], AZ[i][:,1]*p_scaling, linestyle=linestyles[3],
                 color=colors[3], label=label)
        label = None

    if KSTYPE == 1:
        ks_str = "I"
    elif KSTYPE == 2:
        ks_str = "II"
    elif KSTYPE == 3:
        ks_str = "III"
    elif KSTYPE == 4:
        ks_str = "IV"
    elif KSTYPE == 5:
        ks_str = "V"
    else:
        ks_str = str(KSTYPE)

    plt.title(f"{pair} | van Konynenburg and Scott type: " + ks_str)
    leg = plt.legend(loc="best", numpoints=1)
    leg.get_frame().set_linewidth(0.0)
    # plt.ylim([1.0e5*p_scaling, 0.3e7*p_scaling])
    plt.ylabel(r"$P$ (MPa)")
    plt.xlabel(r"$T$ (K)")
    rpair = pair.replace(',', '_')
    plt.savefig(f'{rpair}_GPD_SAFTVRQ.pdf')
    plt.show()
    plt.clf()
```

**Comment by ianhbell** [comment]
We found the ``[get/set]_eps_kij`` and ``[set/get]_sigma_lij`` functions, but even with that, we don't seem to be able to get the same GPD or pxy as published.  Any idea what we might be missing?

**Comment by morteham** [comment]
Thank you for reporting these issues Ian! - And sorry for the inconvenience.

There is a bug in the init, and the quantum corrections are not properly set up. Further the kij/lij are missing in the code.

You can bypass these issues by using
`qSAFT.init(pair,parameter_reference="AASEN2019-FH1")`
and in addition, use `set_eps_kij `and `set_sigma_lij` to set the appropriate interaction parameters.

I will update the code to use AASEN2019-FH1 parameters by default and include the proper kij/lij parameters.

**Comment by ianhbell** [comment]
Thanks for the speedy input, we look forward to having the ability to build the GPD and p-x diagrams from your models.
