### ISSUE TITLE
Using saftvrmie "model_control_xx()" on one instance effects other instances

### ISSUE THREAD

**Issue by vegardjervell** [SINTEF/thermopack#33]
This is similar to an earlier issue where changing parameters in one instance also effected other instances. MRE is simple:

``` 
eos1 = saftvrmie.saftvrmie()
eos1.init(comps)

print(eos1.enable_a1_c, eos1.enable_a2_c, eos1.enable_a3_c, eos1.enable_chain_c, eos1.enable_hs_c)

eos2 = saftvrmie.saftvrmie()
eos2.init(comps)
eos2.model_control_chain(False)
eos2.model_control_a3(False)
eos2.model_control_a2(False)
eos2.model_control_a1(False)

print(eos1.enable_a1_c, eos1.enable_a2_c, eos2.enable_a3_c, eos1.enable_chain_c, eos1.enable_hs_c)
```

outputs
```
c_int(1) c_int(1) c_int(1) c_int(1) c_int(1)
zero
c_int(0) c_int(0) c_int(0) c_int(0) c_int(1)
```

the "zero" is due to a print statement in `model_control_a1()` that is probably just left over from some time. I can definitely work around this for the time being, but it is unexpected behaviour, so I thought it would be nice to post. Unless it's a very easy fix I can add some comments with a warning about the behaviour for the time being.

**Comment by morteham** [comment]
Yes, the parameters of the saftvrmie_options module are global and will affect all models. I will have a look and see if I can add the options to the model specific saftvrmie_eos class.

**Comment by morteham** [comment]
I commited some code making saftvrmie_options local to each eos instance. Can you test and see if it works properly?
