### ISSUE TITLE
pip install (or makescript.py) not working (missing symbols)

### ISSUE THREAD

**Issue by vegardjervell** [SINTEF/thermopack#36]
When I run the standard installation process
```
gmake optim
cd addon/pycThermopack
python makescript.py optim
pip install .
```

The `pyctp`-folder in `addon/pycThermopack/pyctp` contains a single binary, `libthermopack.dynlib`, while my `venv/(...)/pyctp` contains two binaries, `libthermopack.dynlib` and `libthermopack.so`. The issue is that these two files do not export the same symbols. Running

```
nm -gU libthermopack.dynlib > symbols_dynlib.txt
nm -gU libthermopack.so > symbols_so.txt
```

gives the two attached files. 

[symbols in libthermopack.dynlib](https://github.com/SINTEF/thermopack/files/8384327/symbols_dynlib.txt)
[symbols in libthermopack.so](https://github.com/SINTEF/thermopack/files/8384328/symbols_so.txt)

Clearly at least 26 symbols are missing from `libthermopack.so`. Specifically, attempting to initialise anything that inherits from the `thermo`-class will crash with (several) "symbol not found" errors. Looking more closely, there are symbols in both files that are not found in the other, displayed in these files

[symbols only in libthermopack.dynlib](https://github.com/SINTEF/thermopack/files/8384365/only_dynlib_symbols.txt)
[symbols only in libthermopack.so](https://github.com/SINTEF/thermopack/files/8384366/only_so_symbols.txt)

I haven't looked into the details, but found out that I was able to initialize the `saftvrmie` eos simply by running
```
cp libthermopack.dynlib libthermopack.so
```

So I dont know what the symbols in the `.so` file are for, or where they come from, as it appears that only those in the `.dynlib` file are used by the `thermo` class (at least when initializing).

**Comment by morteham** [comment]
I do not understand where the `.so` file come from. If you clear the content of `thermopack/bin/dynamic`  and run `gmake optim` - do you get a `libthermopack.so` file in `thermopack/bin/dynamic`?

If you also delete  `thermopack/addon/pycThermopack/pyctp/libthermopack.*` and execute
```
cd addon/pycThermopack
python makescript.py optim
```
Do you get a `libthermopack.so` file in `thermopack/addon/pycThermopack/pyctp/`?

**Comment by vegardjervell** [comment]
Thats what I was also struggling to figure out. There is no `libthermopack.so` in `/bin/dynamic`, only `libthermopack.dynlib`. Deleting it, and running 
```
gmake clean
gmake optim
```
Does not generate a `.so`, only a `.dynlib`. The same is true for `/addon/pycThermopack/pyctp` and running 
```
cd addon/pycThermopack
python makescript.py optim
```

The only `.so` file I could find was in `addon/pycThermopack/build`, which I see only existed locally for me. I also had a directory `addon/pycThermopack/pyctp.egg-info`. Those have probably been generated by `pip` at some point. Deleting them and running `pip install addon/pycThermopack` installs `pyctp` without any `.so` file, but still gives the missing symbol error.

Renaming the file `venv/(...)/pyctp/libthermopack.dynlib` to `venv/(...)/libthermopack.so` fixes the error.

I think the `.so` file came from some previous, botched, `pip install`. Printing the `pf_specifics` variable on line 25 in `thermo.py` reveals that `platform_specifics.get_platform_specifics()` mistakenly identifies my MacOS-system as a Linux system, and therefore uses the `.so` extension when generating the path to the binary.

I see the `platform_specifics` module was auto-generated on your machine, I've added some lines to `makescript.py` that uses `pyctp/map_platform_specifics.get_platform_specifics_from_platform()` to auto-generate a new `platform_specifics.py` when you run `python makescript.py optim`. This resolved the issue for me, but maybe check that it also works on linux :) Adding a PR at #38
