### ISSUE TITLE
Segfault when using `saftvrmie` with `scipy.minimize()`

### ISSUE THREAD

**Issue by vegardjervell** [SINTEF/thermopack#39]
I cannot figure out what causes this error, but after some testing I've created what I think is a minimal reproducible example at [memory-issues](https://github.com/vegardjervell/thermopack/tree/memory_issues). The code in question is

```
from pyctp import saftvrmie
from scipy.optimize import minimize

class Foo:
    def __init__(self):
        self.eos = saftvrmie.saftvrmie()
        self.eos.init('AR')

    def bar(self):
        def spam(eggs):
            self.baz = 1 # Alternatively: self.eos.helmholtz_tv(300, 10, [50]), or self.dum(), or bac = self.baz, where self.baz is defined elsewhere in Foo
            return abs(eggs)

        self.eos.helmholtz_tv(300, 10, [50])
        self.eos.helmholtz_tv(300, 10, [50])
        solution = minimize(spam, x0=0)
        return 0

    def dum(self):
        pass

for i in range(20):
    f = Foo()
    f.bar()
```
For brevity, I'll call the first instance of `Foo` that is initialized `f_1`, the second `f_2` and so on. Also, `eos_1` is the `saftvrmie` instance belonging to `f_1`, `eos_2` belongs to `f_2` and so on.

This code fails with a segfault in the 4th iteration of the loop, after calling the (implicit) `__del__` method of `f_2`. The segfault occurs after the call to the `delete_eos()` method of `eos_2` has completed, but before the `print` statement at the bottom of the loop executes. I've never hooked up a debugger to a Fortran binary before, but doing that should help in getting the details.

The minimum requirements for causing the error as far as I can see are:

- `self.eos.helmholtz_tv()` must be called *at least* twice inside `bar()`, and the calls must occur *before or during* the call to `minimize()`. Calling other `thermo` methods causes the same behaviour.
- `spam()` must access a member variable or method belonging to `Foo`.
- `bar()` cannot be a free-standing function, it must be a method of `Foo`. The code below executes without issue.
- The same behaviour is not reproduced when using `cubic.cubic()`, although this also crashes with a possibly unrelated error at the 13th iteration of the loop (`EoSlib error in eosTV::Fres: No such EoS libray:           0`). 
- I was unable to create a native Python class that reproduced the error. That, combined with the previous point makes me somewhat confident that this is not an error in `scipy`. However, I was unable to reproduce the error without using `scipy.minimize()`.

Honestly, I'm quite at loss as to exactly where this seemingly very specific issue originates. I would like to say that I am familiar enough with the Fortran-guts of Thermopack to investigate further, but for the time being I think I'll work around it. I guess it is worth being aware of anyway for future development, as there appears to be some funny business going on with memory management.

```
class Foo:
    def __init__(self):
        print('Foo()')
        self.eos =saftvrmie.saftvrmie()
        self.eos.init('AR')
        self.baz = 0

def bar():
    def spam(eggs):
        f.baz = 1
        return abs(eggs)

    f.eos.helmholtz_tv(300, 10, [50])
    f.eos.helmholtz_tv(300, 10, [50])
    solution = minimize(spam, x0=0)
    return 0

for i in range(20):
    f = Foo()
    bar()
```

**Comment by morteham** [comment]
I made one fix that resolved the problem for me. Can you test the attached PR on your side?

**Comment by vegardjervell** [comment]
Awesome, it worked!
