### ISSUE TITLE
Failure due to gcc version detection

### ISSUE THREAD

**Issue by Irvise** [SINTEF/thermopack#6]
Hello,

I am testing Thermopack. After installing it as was indicated in the README, I tried to launch the GUI. However, it failed with the following error:

```
fernando@localhost:~/Builds/thermopack/addon/pycThermopack> python3 thermopack_gui.py 
Traceback (most recent call last):
  File "thermopack_gui.py", line 9, in <module>
    from gui.widgets.component_select_widget import ComponentSelectWidget, ComponentEditWidget
  File "/home/fernando/Builds/thermopack/addon/pycThermopack/gui/widgets/component_select_widget.py", line 6, in <module>
    from gui.utils import get_unique_name, get_fluids, MessageBox
  File "/home/fernando/Builds/thermopack/addon/pycThermopack/gui/utils.py", line 4, in <module>
    from pyctp.cubic import cubic
  File "/home/fernando/Builds/thermopack/addon/pycThermopack/pyctp/__init__.py", line 3, in <module>
    from . import thermo
  File "/home/fernando/Builds/thermopack/addon/pycThermopack/pyctp/thermo.py", line 24, in <module>
    if utils.gcc_major_version_greater_than(7):
  File "/home/fernando/Builds/thermopack/addon/pycThermopack/pyctp/utils.py", line 16, in gcc_major_version_greater_than
    gcc_mv = int(sys_arr_gcc[1].split(".")[0])
ValueError: invalid literal for int() with base 10: ']'
```
## Explanation

The function `gcc_major_version_greater_than(7)` fails. This is because in my system (OpenSuse Tumbleweed) the function `sys.version` in the file `pyctp/utils.py` returns the string `3.8.6 (default, Nov 09 2020, 12:09:06) [GCC]'`. It does not contain information about the GCC version. Because of that, the following lines which try to find it, only find garbage, and the line `gcc_mv = int(sys_arr_gcc[1].split(".")[0])` fails since it does not receive a number.

After I modified the function `gcc_major_version_greater_than()` to always return true (in my case, gcc_version = 10), the cpa.py example ran correctly.

## Proposed solution

Do some error handling to see if the function code fails. If it does I would suggest to return True, after all, gcc > 7 is quite common. CentOS 7 has it (not by default) and CentOS 8 comes with v8 by default. I picked CentOS as my example since it tends to be the slowest moving (and common) Linux out there.

**Comment by morteham** [comment]
Thanks Irvise for reporting this issue!

I have rewritten the `gcc_major_version_greater_than()` to use subprocess, and catch the output of `gcc --version`. Hopefully this will aslo work with CentOS.
