### ISSUE TITLE
Build system advice

### ISSUE THREAD

**Issue by ibell** [SINTEF/thermopack#8]
Have you considered to convert the meta-build systems to run on CMake? It simplifies life tremendously for users, especially windows users, and full-stack project integration (without copy-pasting of objects/libraries) is possible. This is especially important for making sure that linking flags are consistent across object boundaries (matching static and dynamic linking).

Also, docker might be the better solution for windows users; I have always run away from anything that needs MSYS2.

Anyway, glad to see thermopack made it to github!

**Comment by morteham** [comment]
Thank you for your input Ian!

Yes, we have considered CMake for building Thermopack, and will probably set up CMake some time in the future. But I can't promise when....

Usually when working on Windows we run thermopack in a VirtualBox with linux as a guest OS. However some of my collegues use MSYS2. I have no experience with docker, but I will check it out, to see if and how we can use docker containers for thermopack. Making some precompiled version of thermopack available, to be used together with the pyhton interface, would also make life easier for most Windows users.

Regards,
Morten
